import React, { createContext, useState, useContext, useEffect } from 'react';

export const translations = {
  en: {
    // General
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    profile: "Profile",
    close: "Close",
    send: "Send Message",
    
    // Onboarding
    experienceFuture: "Experience the Future of Cognition",
    unlockPower: "Unlock the power of MAYA COGNITION. Your personalized companion for creativity, productivity, and complex problem-solving.",
    getStarted: "Get Started",
    signIn: "Sign In",
    explore: "Explore",
    neuralEngine: "Maya Neural Engine v4.0",
    privacyEncrypted: "Privacy Encrypted",
    
    // Login / Sign Up
    welcomeBack: "Welcome back to the future of cognition.",
    createAccount: "Create your neural profile.",
    emailAddress: "EMAIL ADDRESS",
    password: "PASSWORD",
    forgot: "Forgot?",
    orContinueWith: "OR CONTINUE WITH",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    signUp: "Sign Up",
    
    // Chat
    askMaya: "Ask Maya anything...",
    howCanIHelp: "How Can I Help",
    mayaAssistant: "I'm MAYA, your advanced neural assistant. Ask me anything to get started.",
    processing: "Processing...",
    writeCode: "Write code",
    explainAI: "Explain AI",
    brainstorm: "Brainstorm",
    history: "History",
    clearChat: "Clear Chat",
    noHistoryYet: "No history yet",
    
    // Profile
    myProfile: "MY PROFILE",
    pro: "MAYA+",
    themePreferences: "Theme Preferences",
    darkModeActive: "Dark mode active",
    lightModeActive: "Light mode active",
    pricingPlans: "Pricing & Plans",
    appSettings: "App Settings",
    contactSupport: "Contact Support",
    logOut: "Log Out",
    securelyEndSession: "Securely end your session",
    
    // Settings
    application: "APPLICATION",
    notifications: "Notifications",
    language: "Language",
    aiData: "AI & DATA",
    privacySecurity: "Privacy & Security",
    support: "SUPPORT",
    helpCenter: "Help Center",
    termsOfService: "Terms of Service",
    selectLanguage: "Select Language",
    
    // Privacy & Security Modal
    privacyTitle: "Privacy & Security",
    dataEncryption: "End-to-End Encryption",
    dataEncryptionDesc: "All your conversations are encrypted with AES-256 standard. No one, not even Maya, can read your private logs without authorization.",
    neuralPrivacy: "Neural Privacy",
    neuralPrivacyDesc: "Your data is used solely to enhance your personalized model. We never sell your data to third parties.",
    accountSecurity: "Account Integrity",
    accountSecurityDesc: "Multi-factor authentication and biometric locks ensure that only you can access your cognitive profile.",

    // Terms of Service Modal
    termsTitle: "Terms of Service",
    userConduct: "User Conduct",
    userConductDesc: "Users must interact with Maya respectfully. Any attempt to exploit or misuse the neural engine will result in account termination.",
    dataUsage: "Data Usage",
    dataUsageDesc: "By using Maya, you agree to our data processing guidelines. We prioritize your privacy above all else.",
    intellectualProperty: "Intellectual Property",
    intellectualPropertyDesc: "All responses generated by Maya are the intellectual property of the user, provided they comply with our safety guidelines.",

    // Contact Page
    contactTitle: "CONTACT SUPPORT",
    hereToHelp: "We're here to help",
    neuralSupport: "Get in touch with our neural support team.",
    fullName: "FULL NAME",
    message: "MESSAGE",
    messageSent: "Message Sent!",
    callback: "Callback",
    liveChat: "Live Chat",
    email: "Email",
    placeholderName: "Enter your name",
    placeholderEmail: "name@example.com",
    placeholderMessage: "How can we help you?",
    thankYou: "We'll get back to you within 24 hours.",
    sendAnother: "Send Another",

    // History Page
    cognitionHistory: "COGNITION HISTORY",
    recentConversations: "RECENT CONVERSATIONS",
    clearAllHistory: "Clear All History",
    noRecordsFound: "No records found",
    confirmClear: "Are you sure you want to clear all history?",
    
    // Explore
    exploreMaya: "EXPLORE MAYA",
    discoverNext: "Discover the next generation of conversational intelligence and productivity.",
    aiCapabilities: "AI Capabilities",
    aiDescription: "MAYA COGNITION leverages our advanced Neural Engine v4.0 to understand complex queries, generate programming code, write creative content, and synthesize large amounts of data in milliseconds.",
    keyFeatures: "Key Features",
    featureMemory: "Contextual Memory",
    featureMemoryDesc: "Remembers your past interactions for seamless follow-ups.",
    featureCode: "Code Execution",
    featureCodeDesc: "Generates and formats code blocks natively.",
    featureVoice: "Voice Input",
    featureVoiceDesc: "Speak naturally instead of typing your queries.",
    featureMultiLang: "Multi-Language Support",
    featureMultiLangDesc: "Instantly switch between English, Hindi, and Telugu.",
    howItWorks: "How It Works",
    howItWorksDesc: "Simply type or speak your request into the chat interface. MAYA COGNITION processes your intent through secure, cloud-based neural pathways and returns highly accurate, context-aware responses instantly.",
    benefits: "Benefits",
    benefitsDesc: "Boost your productivity, solve problems faster, and brainstorm effortlessly. All your data is privacy-encrypted, ensuring a safe and secure digital companion experience.",
  },
  hi: {
    // General
    back: "पीछे",
    cancel: "रद्द करें",
    save: "सहेजें",
    profile: "प्रोफ़ाइल",
    close: "बंद करें",
    send: "संदेश भेजें",

    // Onboarding
    experienceFuture: "अनुभूति के भविष्य का अनुभव करें",
    unlockPower: "MAYA COGNITION की शक्ति को अनलॉक करें। रचनात्मकता, उत्पादकता और जटिल समस्याओं को सुलझाने के लिए आपका व्यक्तिगत साथी।",
    getStarted: "शुरू करें",
    signIn: "साइन इन करें",
    explore: "अन्वेषण करें",
    neuralEngine: "माया न्यूरल इंजन v4.0",
    privacyEncrypted: "गोपनीयता एन्क्रिप्टेड",
    
    // Login / Sign Up
    welcomeBack: "अनुभूति के भविष्य में वापस स्वागत है।",
    createAccount: "अपनी न्यूरल प्रोफाइल बनाएं।",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    forgot: "भूल गए?",
    orContinueWith: "या इसके साथ जारी रखें",
    dontHaveAccount: "क्या आपका खाता नहीं है?",
    alreadyHaveAccount: "क्या आपके पास पहले से खाता है?",
    signUp: "साइन अप करें",
    
    // Chat
    askMaya: "Maya से कुछ भी पूछें...",
    howCanIHelp: "मैं आपकी कैसे मदद कर सकता हूँ",
    mayaAssistant: "मैं MAYA हूँ, आपकी उन्नत न्यूरल सहायक। शुरू करने के लिए मुझसे कुछ भी पूछें।",
    processing: "प्रोसेसिंग...",
    writeCode: "कोड लिखें",
    explainAI: "AI समझाएं",
    brainstorm: "विचार मंथन",
    history: "इतिहास",
    clearChat: "चैट साफ़ करें",
    noHistoryYet: "अभी तक कोई इतिहास नहीं",
    
    // Profile
    myProfile: "मेरी प्रोफाइल",
    pro: "MAYA+",
    themePreferences: "थीम प्राथमिकताएं",
    darkModeActive: "डार्क मोड सक्रिय",
    lightModeActive: "लाइट मोड सक्रिय",
    pricingPlans: "मूल्य निर्धारण और योजनाएं",
    appSettings: "ऐप सेटिंग्स",
    contactSupport: "सहायता से संपर्क करें",
    logOut: "लॉग आउट करें",
    securelyEndSession: "अपना सत्र सुरक्षित रूप से समाप्त करें",
    
    // Settings
    application: "एप्लिकेशन",
    notifications: "सूचनाएं",
    language: "भाषा",
    aiData: "AI और डेटा",
    privacySecurity: "गोपनीयता और सुरक्षा",
    support: "समर्थन",
    helpCenter: "सहायता केंद्र",
    termsOfService: "सेवा की शर्तें",
    selectLanguage: "भाषा चुनें",
    
    // Privacy & Security Modal
    privacyTitle: "गोपनीयता और सुरक्षा",
    dataEncryption: "एंड-टू-एंड एन्क्रिप्शन",
    dataEncryptionDesc: "आपकी सभी बातचीत AES-256 मानक के साथ एन्क्रिप्टेड हैं। कोई भी, यहां तक कि माया भी, प्राधिकरण के बिना आपके निजी लॉग नहीं पढ़ सकता है।",
    neuralPrivacy: "न्यूरल गोपनीयता",
    neuralPrivacyDesc: "आपके डेटा का उपयोग पूरी तरह से आपके व्यक्तिगत मॉडल को बढ़ाने के लिए किया जाता है। हम कभी भी आपका डेटा तीसरे पक्ष को नहीं बेचते हैं।",
    accountSecurity: "खाता अखंडता",
    accountSecurityDesc: "मल्टी-फैक्टर ऑथेंटिकेशन और बायोमेट्रिक लॉक यह सुनिश्चित करते हैं कि केवल आप ही अपनी संज्ञानात्मक प्रोफाइल तक पहुंच सकें।",

    // Terms of Service Modal
    termsTitle: "सेवा की शर्तें",
    userConduct: "उपयोगकर्ता आचरण",
    userConductDesc: "उपयोगकर्ताओं को माया के साथ सम्मानपूर्वक बातचीत करनी चाहिए। न्यूरल इंजन का शोषण या दुरुपयोग करने के किसी भी प्रयास के परिणामस्वरूप खाता समाप्त कर दिया जाएगा।",
    dataUsage: "डेटा उपयोग",
    dataUsageDesc: "माया का उपयोग करके, आप हमारे डेटा प्रोसेसिंग दिशानिर्देशों से सहमत होते हैं। हम आपकी गोपनीयता को सबसे ऊपर रखते हैं।",
    intellectualProperty: "बौद्धिक संपदा",
    intellectualPropertyDesc: "माया द्वारा उत्पन्न सभी प्रतिक्रियाएं उपयोगकर्ता की बौद्धिक संपदा हैं, बशर्ते वे हमारे सुरक्षा दिशानिर्देशों का पालन करती हों।",

    // Contact Page
    contactTitle: "सहायता से संपर्क करें",
    hereToHelp: "हम यहाँ मदद के लिए हैं",
    neuralSupport: "हमारी न्यूरल सपोर्ट टीम से संपर्क करें।",
    fullName: "पूरा नाम",
    message: "संदेश",
    messageSent: "संदेश भेज दिया गया!",
    callback: "कॉल बैक",
    liveChat: "लाइव चैट",
    email: "ईमेल",
    placeholderName: "अपना नाम दर्ज करें",
    placeholderEmail: "name@example.com",
    placeholderMessage: "हम आपकी कैसे मदद कर सकते हैं?",
    thankYou: "हम 24 घंटे के भीतर आपसे संपर्क करेंगे।",
    sendAnother: "एक और भेजें",

    // History Page
    cognitionHistory: "अनुभूति इतिहास",
    recentConversations: "हाल की बातचीत",
    clearAllHistory: "सभी इतिहास साफ़ करें",
    noRecordsFound: "कोई रिकॉर्ड नहीं मिला",
    confirmClear: "क्या आप वाकई सभी इतिहास साफ़ करना चाहते हैं?",
    
    // Explore
    exploreMaya: "MAYA का अन्वेषण करें",
    discoverNext: "संवादात्मक बुद्धिमत्ता और उत्पादकता की अगली पीढ़ी की खोज करें।",
    aiCapabilities: "AI क्षमताएं",
    aiDescription: "MAYA COGNITION जटिल प्रश्नों को समझने, प्रोग्रामिंग कोड उत्पन्न करने, रचनात्मक सामग्री लिखने और मिलीसेकंड में बड़ी मात्रा में डेटा को संश्लेषित करने के लिए हमारे उन्नत न्यूरल इंजन v4.0 का लाभ उठाता है।",
    keyFeatures: "प्रमुख विशेषताएं",
    featureMemory: "प्रासंगिक स्मृति",
    featureMemoryDesc: "निर्बाध अनुवर्ती कार्रवाई के लिए आपकी पिछली बातचीत को याद रखता है।",
    featureCode: "कोड निष्पादन",
    featureCodeDesc: "मूल रूप से कोड ब्लॉक उत्पन्न और स्वरूपित करता है।",
    featureVoice: "वॉयस इनपुट",
    featureVoiceDesc: "अपने प्रश्नों को टाइप करने के बजाय स्वाभाविक रूप से बोलें।",
    featureMultiLang: "बहु-भाषा समर्थन",
    featureMultiLangDesc: "अंग्रेजी, हिंदी और तेलुगु के बीच तुरंत स्विच करें।",
    howItWorks: "यह कैसे काम करता है",
    howItWorksDesc: "बस चैट इंटरफ़ेस में अपना अनुरोध टाइप करें या बोलें। MAYA COGNITION सुरक्षित, क्लाउड-आधारित न्यूरल मार्गों के माध्यम से आपके इरादे को संसाधित करता है और तुरंत अत्यधिक सटीक, संदर्भ-जागरूक प्रतिक्रिया देता है।",
    benefits: "लाभ",
    benefitsDesc: "अपनी उत्पादकता बढ़ाएँ, समस्याओं को तेज़ी से हल करें और सहजता से विचार-मंथन करें। आपका सारा डेटा गोपनीयता-एन्क्रिप्टेड है, जो एक सुरक्षित और सुरक्षित डिजिटल साथी अनुभव सुनिश्चित करता है।",
  },
  te: {
    // General
    back: "వెనుకకు",
    cancel: "రద్దు చేయి",
    save: "సేవ్ చేయి",
    profile: "ప్రొఫైల్",
    close: "మూసివేయి",
    send: "సందేశం పంపండి",

    // Onboarding
    experienceFuture: "జ్ఞానం యొక్క భవిష్యత్తును అనుభవించండి",
    unlockPower: "MAYA COGNITION శక్తిని అన్‌లాక్ చేయండి. సృజనాత్మకత, ఉత్పాదకత మరియు సంక్లిష్ట సమస్యలను పరిష్కరించడానికి మీ వ్యక్తిగత సహచరుడు.",
    getStarted: "ప్రారంభించండి",
    signIn: "సైన్ ఇన్ చేయండి",
    explore: "అన్వేషించండి",
    neuralEngine: "మాయ న్యూరల్ ఇంజిన్ v4.0",
    privacyEncrypted: "గోప్యత ఎన్‌క్రిప్ట్ చేయబడింది",
    
    // Login / Sign Up
    welcomeBack: "జ్ఞానం యొక్క భవిష్యత్తుకు తిరిగి స్వాగతం.",
    createAccount: "మీ న్యూరల్ ప్రొఫైల్‌ను సృష్టించండి.",
    emailAddress: "ఇమెయిల్ చిరునామా",
    password: "పాస్వర్డ్",
    forgot: "మర్చిపోయారా?",
    orContinueWith: "లేదా దీని ద్వారా కొనసాగించండి",
    dontHaveAccount: "ఖాతా లేదా?",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    signUp: "సైన్ అప్ చేయండి",
    
    // Chat
    askMaya: "Maya ని ఏదైనా అడగండి...",
    howCanIHelp: "నేను ఎలా సహాయపడగలను",
    mayaAssistant: "నేను MAYA ని, మీ అధునాతన న్యూరల్ అసిస్టెంట్ ని. ప్రారంభించడానికి నన్ను ఏదైనా అడగండి.",
    processing: "ప్రాసెస్ అవుతోంది...",
    writeCode: "కోడ్ రాయండి",
    explainAI: "AI గురించి వివరించండి",
    brainstorm: "ఆలోచనలు చేయండి",
    history: "చరిత్ర",
    clearChat: "చాట్ క్లియర్ చేయండి",
    noHistoryYet: "ఇంకా చరిత్ర లేదు",
    
    // Profile
    myProfile: "నా ప్రొఫైల్",
    pro: "MAYA+",
    themePreferences: "థీమ్ ప్రాధాన్యతలు",
    darkModeActive: "డార్క్ మోడ్ యాక్టివ్",
    lightModeActive: "లైట్ మోడ్ యాక్టివ్",
    pricingPlans: "ధరలు & ప్లాన్‌లు",
    appSettings: "యాప్ సెట్టింగ్‌లు",
    contactSupport: "మద్దతును సంప్రదించండి",
    logOut: "లాగ్ అవుట్ చేయండి",
    securelyEndSession: "మీ సెషన్‌ను సురక్షితంగా ముగించండి",
    
    // Settings
    application: "అప్లికేషన్",
    notifications: "నోటిఫికేషన్లు",
    language: "భాష",
    aiData: "AI & డేటా",
    privacySecurity: "గోప్యత & భద్రత",
    support: "మద్దతు",
    helpCenter: "సహాయ కేంద్రం",
    termsOfService: "సేవా నిబంధనలు",
    selectLanguage: "భాషను ఎంచుకోండి",
    
    // Privacy & Security Modal
    privacyTitle: "గోప్యత & భద్రత",
    dataEncryption: "ఎండ్-టు-ఎండ్ ఎన్‌క్రిప్షన్",
    dataEncryptionDesc: "మీ సంభాషణలన్నీ AES-256 ప్రమాణంతో ఎన్‌క్రిప్ట్ చేయబడ్డాయి. అనుమతి లేకుండా మాయ కూడా మీ ప్రైవేట్ లాగ్‌లను చదవలేదు.",
    neuralPrivacy: "న్యూరల్ ప్రైవసీ",
    neuralPrivacyDesc: "మీ డేటా కేవలం మీ వ్యక్తిగత నమూనాను మెరుగుపరచడానికి మాత్రమే ఉపయోగించబడుతుంది. మేము మీ డేటాను ఎప్పుడూ థర్డ్ పార్టీలకు విక్రయించము.",
    accountSecurity: "ఖాతా సమగ్రత",
    accountSecurityDesc: "మల్టీ-ఫాక్టర్ అథెంటికేషన్ మరియు బయోమెట్రిక్ లాక్‌లు మీరు మాత్రమే మీ కాగ్నిటివ్ ప్రొఫైల్‌ను యాక్సెస్ చేయగలరని నిర్ధారిస్తాయి.",

    // Terms of Service Modal
    termsTitle: "సేవా నిబంధనలు",
    userConduct: "వినియోగదారు ప్రవర్తన",
    userConductDesc: "వినియోగదారులు మాయతో గౌరవప్రదంగా సంభాషించాలి. న్యూరల్ ఇంజిన్‌ను దుర్వినియోగం చేసే ఏ ప్రయత్నమైనా ఖాతా రద్దుకు దారితీస్తుంది.",
    dataUsage: "డేటా వినియోగం",
    dataUsageDesc: "మాయను ఉపయోగించడం ద్వారా, మీరు మా డేటా ప్రాసెసింగ్ మార్గదర్శకాలకు అంగీకరిస్తారు. మేము మీ గోప్యతకు అత్యంత ప్రాధాన్యత ఇస్తాము.",
    intellectualProperty: "మేధో సంపత్తి",
    intellectualPropertyDesc: "మాయ ద్వారా రూపొందించబడిన ప్రతిస్పందనలన్నీ వినియోగదారు యొక్క మేధో సంపత్తి, అవి మా భద్రతా మార్గదర్శకాలకు అనుగుణంగా ఉంటే.",

    // Contact Page
    contactTitle: "మద్దతును సంప్రదించండి",
    hereToHelp: "మేము సహాయం చేయడానికి ఇక్కడ ఉన్నాము",
    neuralSupport: "మా న్యూరల్ సపోర్ట్ టీమ్‌ని సంప్రదించండి.",
    fullName: "పూర్తి పేరు",
    message: "సందేశం",
    messageSent: "సందేశం పంపబడింది!",
    callback: "కాల్ బ్యాక్",
    liveChat: "లైవ్ చాట్",
    email: "ఇమెయిల్",
    placeholderName: "మీ పేరును నమోదు చేయండి",
    placeholderEmail: "name@example.com",
    placeholderMessage: "మేము మీకు ఎలా సహాయపడగలము?",
    thankYou: "మేము 24 గంటల్లోపు మిమ్మల్ని సంప్రదిస్తాము.",
    sendAnother: "మరొకటి పంపండి",

    // History Page
    cognitionHistory: "జ్ఞాన చరిత్ర",
    recentConversations: "ఇటీవలి సంభాషణలు",
    clearAllHistory: "మొత్తం చరిత్రను క్లియర్ చేయండి",
    noRecordsFound: "రికార్డులు ఏవీ కనుగొనబడలేదు",
    confirmClear: "మీరు ఖచ్చితంగా మొత్తం చరిత్రను క్లియర్ చేయాలనుక్యున్నారా?",
    
    // Explore
    exploreMaya: "MAYA ని అన్వేషించండి",
    discoverNext: "తదుపరి తరం సంభాషణ మేధస్సు మరియు ఉత్పాదకతను కనుగొనండి.",
    aiCapabilities: "AI సామర్థ్యాలు",
    aiDescription: "MAYA COGNITION సంక్లిష్టమైన ప్రశ్నలను అర్థం చేసుకోవడానికి, ప్రోగ్రామింగ్ కోడ్‌ను రూపొందించడానికి, సృజనాత్మక కంటెంట్‌ను వ్రాయడానికి మరియు మిల్లీసెకన్లలో భారీ మొత్తంలో డేటాను సంశ్లేషణ చేయడానికి మా అధునాతన న్యూరల్ ఇంజిన్ v4.0ని ప్రభవైతం చేస్తుంది.",
    keyFeatures: "ముఖ్య లక్షణాలు",
    featureMemory: "సందర్భోచిత మెమరీ",
    featureMemoryDesc: "అతుకులు లేని తదుపరి చర్యల కోసం మీ గత పరస్పర చర్యలను గుర్తుంది.",
    featureCode: "కోడ్ అమలు",
    featureCodeDesc: "కోడ్ బ్లాక్‌లను స్థానికంగా రూపొందిస్తుంది మరియు ఫార్మాట్ చేస్తుంది.",
    featureVoice: "వాయిస్ ఇన్‌పుట్",
    featureVoiceDesc: "మీ ప్రశ్నలను టైప్ చేసే బదులు సహజంగా మాట్లాడండి.",
    featureMultiLang: "బహుళ భాషా మద్దతు",
    featureMultiLangDesc: "ఇంగ్లీష్, హిందీ మరియు తెలుగు మధ్య తక్షణమే మారండి.",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    howItWorksDesc: "చాట్ ఇంటర్‌ఫేస్‌లో మీ అభ్యర్థనను టైప్ చేయండి లేదా మాట్లాడండి. MAYA COGNITION సురక్షితమైన, క్లౌడ్-ఆధారిత న్యూరల్ పాత్‌వేల ద్వారా మీ ఉద్దేశాన్ని ప్రాసెస్ చేస్తుంది మరియు తక్షణమే అత్యంత ఖచ్చితమైన, సందర్భోచిత ప్రతిస్పందనలను అందిస్తుంది.",
    benefits: "ప్రయోజనాలు",
    benefitsDesc: "మీ ఉత్పాదకతను పెంచుకోండి, సమస్యలను వేగంగా పరిష్కరించండి మరియు అప్రయత్నంగా ఆలోచనలు చేయండి. మీ డేటా అంతా ప్రైవసీ-ఎన్‌క్రిప్ట్ చేయబడింది, సురక్షితమైన మరియు భద్రమైన డిజిటల్ సహచర అనుభవాన్ని నిర్ధారిస్తుంది.",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('mayaLanguage');
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('mayaLanguage', lang);
  };

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
